### ISSUE TITLE
No se aplicó correctamente la metodología

### ISSUE THREAD

**Issue by evolentini** [SAlmandos2/TSSE-TP3#3]
Las pruebas deben fallar cuando se las escribe, una prueba que no falla al inicio no prueba nada, esta por ejemplo

https://github.com/SAlmandos2/TSSE-TP3/blob/25216f4b387f5dc37b172034b755932d53ee8d88/test/test_leds.c#L59-L64

Dado que todos los leds arrancan apagados, apagar leds apagados no es una prueba de nada. Sin embargo el código de la función `Leds_TurnOffAll()` esta completo, lo que implica que tampoco se respetó la regla de escribir el código mínimo para resolver el problema de la falla, sino que se escribió todo el código de una vez.

**Comment by SAlmandos2** [comment]
Es verdad, el de TurnOffAll lo hice en conjunto con el de TurnOnAll... se me paso por alto

**Comment by evolentini** [comment]
Lo más razonable era prender todos con la función que definiste en la prueba anterior y despues apagarlos todos para probar la nueva función.
