### ISSUE TITLE
Se puede refactorizar el código

### ISSUE THREAD

**Issue by evolentini** [SAlmandos2/TSSE-TP3#4]
Dado que todos los led arrancan apagados sería buena idea reemplazar esta linea

https://github.com/SAlmandos2/TSSE-TP3/blob/25216f4b387f5dc37b172034b755932d53ee8d88/src/leds.c#L11

por una llamada a la función `Led_TurnOffAll()`

**Comment by SAlmandos2** [comment]
Perfecto. esto sucedería cuando hago la depuración de la prueba de TurnOffAll?
